### ISSUE TITLE
API can connect to MongoDB 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot-api#1]
# Motivation
We are using this as an endpoint to eventually, talk to our microservice application. Also because I want to learn how to use MongoDB

# Task implementation
- [x] Learn about mongoDB
- [x] Create Mongo Lab account
- [x] Attain knowledge on MongoDB Queries
- [x] Connect Mongo Cloud account to my API
