### ISSUE TITLE
API Can C/R/D Swears

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot-api#2]
# Motivation
We want to be able to add swears to the database. This will be tied to both the server, and the word, which are unique pairs. 

We also want to allow flexibility, in that if a word is already in the database, do nothing. Otherwise, add the word. The server-word pairing should be unique. 

We should also add for partial query completion. If the query has some words that are not in the database, and some that are, then allow the query to partially complete. The words that are in there, should not be added, and the ones that are not should be added. 

# Task implementation
- [x] Create a route to be able to route these requests. 
- [x] Be able to also serve the database inside the query.
- [x] Be able to gather the swears to be added.
- [x] Be able to create HTTPIE requests to add these. 
- [x] Verify that the request worked. 
- [x] Verify on Mongo Lab that the entries were indeed created. 
- [x] Verify that the words are indeed in the database.
- [x] Verify that the words aren't being duplicated, and that the queries are being entered in correctly. 
- [x] Create a route to be able to DELETE words.
- [x] Test it thoroughly.
- [x] Verify the results are correct. 
- [X] Refactor this part.

**Comment by kennykimjr** [comment]
Note to self: I should look upon re-visiting this branch so that I can CRUD the swears too. We want to be able to delete words that we don't feel are that offensive anymore. 

Also, we should be going ahead and figuring out how to modular-ize express for later.

**Comment by kennykimjr** [comment]
Re-opening since I want to also go back and implement swear-deletion as well.
