### ISSUE TITLE
API Can CRUD Server Settings

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot-api#4]
# Motivation

We want to be able to get the server settings for each server with the API. If the server config does not exist, then we'll tell the server to make one, and then store that into the DB. 

# Task implementation
- [x] Create a route to get a server config. 
- [x] By extension, if the server config does not exist, make one. 
- [x] Create a route to create a server server config in the case that the config doesn't exist. 
- [x] Create a file to store all the relevant controls and settings for a server. 
- [x] Add a route to delete a server config.
- [x] Add a route to update a server config.
- [x] Verify results.
- [ ] Re-factor the code base.

**Comment by kennykimjr** [comment]
Re-opening this to re-factor code.
