### ISSUE TITLE
API Can CRUD User Strikes

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot-api#5]
# Motivation
We want to be able to get the user strikes from a user and a server. This will be targeted towards unique pairs of getting users and servers. 

# Task Implementation
- [x] Create a route to create a pair of userid, serverid, and number of strikes.
- [x] Create a route to Get this unique pair. 
- [x] Change the get server docs function to be able to handle any given query. 
- [x] Change the resolve difference docs to be able to resolve any new documents. 
- [x] Create a put route to update the user strikes if they exist already. Ideally, this should do nothing if the user does not exist. 
- [x] In the case that there aren't any records for that user, return 0. 
- [x] Re-factor code to match format of Issue-2

**Comment by kennykimjr** [comment]
Re-opening this since I want to re-factor the code for this part. Avoiding more callback hell would be nice.
