### ISSUE TITLE
API can C/R/D Blacklisted URL's

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot-api#6]
# Motivation
We want to be able to block url's or links that we could be perceived as dangerous, spammy or unhelpful. In a way, this is a very similar problem to 

# Task implementation
- [x] Create a new file to route the links.
- [x] Create a route to POST new URL's.
- [x] Make sure that the entries are not duplicated.
- [x] Create a route to GET new URL's 
- [x] Verify Results. 
- [x] Test repeatedly. 
- [x] Create a route to GET the new URL's by server. 
- [x] Verify Results. Test Repeatedly. 
- [x] Create a route to DELETE URL's.
- [x] Verify Results. Test Repeatedly. 
- [x] Add the new routes to the main index.js file.
