### ISSUE TITLE
User can CRUD Commands

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot-api#7]
# Motivation
We want to be able to be able to configure commands.

# Task Implementation
- [x] Create a route to get these commands.
- [x] Create a route to add these commands.
- [x] Create a route to update these commands.
- [x] Create a route to delete these commands.
- [x] Pool the routes into the main app.
- [x] Perform unit tests.
